'use client';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowUpRight, Check, FileText, Image, ScanText, Sparkles, Layers3, WandSparkles, Zap } from 'lucide-react';

const tools = [
    { title: 'PDF to DOCX', detail: 'Turn locked layouts into editable documents.', icon: FileText, href: '/tools/pdf-to-docx', tone: 'bg-[#dce9df]' },
    { title: 'OCR extractor', detail: 'Pull clean, usable text from scans.', icon: ScanText, href: '/tools/ocr', tone: 'bg-[#f9dfd3]' },
    { title: 'Remove background', detail: 'Create transparent product cutouts with AI.', icon: WandSparkles, href: '/tools/remove-bg', tone: 'bg-[#e8e1f0]' },
    { title: 'Image composer', detail: 'Layer, crop, annotate, and export images.', icon: Image, href: '/tools/image-composer', tone: 'bg-[#f2e5b9]' },
    { title: 'Batch converter', detail: 'Process up to 20 files in one queue.', icon: Layers3, href: '/tools/batch-converter', tone: 'bg-[#d9e4ec]' },
];

export default function Home() {
    return <main className="noise min-h-screen overflow-hidden">
        <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><Link href="/" className="flex items-center gap-2 text-lg font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-coral text-white"><Sparkles size={16} /></span> format<span className="text-coral">.</span></Link><div className="hidden items-center gap-8 text-sm text-slate-600 md:flex"><a href="#tools">Tools</a><a href="#promise">Why local-first</a><span className="h-5 w-px bg-line" /><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-moss" /> Files stay yours</span></div><button className="rounded-full border border-ink px-4 py-2 text-sm font-semibold hover:bg-ink hover:text-white">GitHub <ArrowUpRight size={14} className="ml-1 inline" /></button></nav>
        <section className="mx-auto max-w-7xl px-6 pb-20 pt-12 lg:px-10 lg:pb-28 lg:pt-20"><div className="grid items-end gap-12 lg:grid-cols-[1.2fr_.8fr]"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}><p className="mb-6 flex items-center gap-2 text-sm font-semibold uppercase tracking-[.18em] text-coral"><Zap size={15} /> file work, without the fuss</p><h1 className="max-w-4xl font-display text-6xl leading-[.95] tracking-tight sm:text-7xl lg:text-8xl">Make files<br /><span className="text-moss">move faster.</span></h1><p className="mt-8 max-w-lg text-lg leading-8 text-slate-600">A calm, capable toolkit for the conversions, edits, and clean-up jobs that pile up between ideas.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#tools" className="rounded-full bg-ink px-6 py-3.5 text-sm font-bold text-white transition hover:bg-moss">Explore the toolkit <ArrowUpRight className="ml-2 inline" size={16} /></Link><span className="flex items-center gap-2 px-3 text-sm text-slate-500"><Check size={16} className="text-moss" /> No account needed</span></div></motion.div><motion.div initial={{ opacity: 0, scale: .95 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .15, duration: .55 }} className="relative mx-auto w-full max-w-md"><div className="absolute -right-3 -top-5 rotate-3 rounded-xl bg-coral px-4 py-3 text-sm font-bold text-white shadow-lg">Drop it here.</div><div className="rounded-[2rem] border border-[#cbd4ca] bg-white/70 p-4 shadow-[0_24px_70px_rgba(69,107,91,.12)]"><div className="rounded-[1.5rem] bg-moss p-7 text-white"><p className="text-sm text-white/70">Your workspace</p><p className="mt-12 font-display text-4xl">5 tools.<br />One clear head.</p><div className="mt-14 flex items-center justify-between border-t border-white/20 pt-4 text-xs text-white/70"><span>Local-first processing</span><span>01 / 05</span></div></div></div></motion.div></div></section>
        <section id="tools" className="border-y border-line bg-[#eeece4] px-6 py-16 lg:px-10 lg:py-20"><div className="mx-auto max-w-7xl"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.16em] text-coral">The toolkit</p><h2 className="font-display text-4xl">Pick a starting point.</h2></div><p className="hidden max-w-xs text-right text-sm leading-6 text-slate-500 md:block">Small tools for the moments when a file gets in the way of the work.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{tools.map((tool, index) => { const Icon = tool.icon; return <motion.div key={tool.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .07 }}><Link href={tool.href} className={`tool-card block h-full rounded-2xl border border-transparent ${tool.tone} p-5`}><div className="mb-16 flex items-start justify-between"><Icon size={25} strokeWidth={1.5} /><ArrowUpRight size={18} /></div><h3 className="font-semibold">{tool.title}</h3><p className="mt-2 text-sm leading-5 text-slate-600">{tool.detail}</p></Link></motion.div>; })}</div></div></section>
        <section id="promise" className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-16 lg:flex-row lg:items-center lg:justify-between lg:px-10"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.16em] text-coral">A better default</p><h2 className="font-display text-4xl">Private by design.<br />Practical by nature.</h2></div><div className="grid max-w-2xl gap-6 sm:grid-cols-3"><div><p className="font-semibold">Local-first</p><p className="mt-2 text-sm leading-6 text-slate-500">Images can stay in your browser. Less uploading, more control.</p></div><div><p className="font-semibold">Open source</p><p className="mt-2 text-sm leading-6 text-slate-500">A transparent stack you can run and extend yourself.</p></div><div><p className="font-semibold">No clutter</p><p className="mt-2 text-sm leading-6 text-slate-500">Focused tools that get out of the way when the job is done.</p></div></div></section>
        <footer className="border-t border-line px-6 py-7 text-sm text-slate-500 lg:px-10"><div className="mx-auto flex max-w-7xl justify-between"><span>format studio / 2026</span><span>built for the in-between work</span></div></footer>
    </main>;
}
